# Generated by Django 4.2.12 on 2025-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons/categories/', verbose_name='Иконка категории'),
        ),
    ]
