# Generated by Django 4.2.12 on 2025-01-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_category_sub_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='title',
        ),
    ]
