# Generated by Django 4.2.12 on 2025-01-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_category_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_name',
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_en',
            field=models.CharField(default='White', max_length=150, verbose_name='Цвет товара en'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_ru',
            field=models.CharField(default='Белый', max_length=150, verbose_name='Цвет товара ru'),
        ),
    ]
