# Generated by Django 5.1.5 on 2025-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=70, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия получателя'),
        ),
    ]
