# Generated by Django 5.1.5 on 2025-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_color_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Цвет товара'),
        ),
    ]
