# Generated by Django 5.1.5 on 2025-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_or_flat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='user',
            name='house_or_block',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом/Корпус'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
